// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeieJgC9ieJtEeobM2CaihrxdrcX593qc',
    appId: '1:941281553238:android:679777b9eb994ec12284f7',
    messagingSenderId: '941281553238',
    projectId: 'ed-sentre',
    storageBucket: 'ed-sentre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7A-cqil_F5uEKVfe7TYFyfxRcdalVdC4',
    appId: '1:941281553238:ios:730a4ca7b8cfd57b2284f7',
    messagingSenderId: '941281553238',
    projectId: 'ed-sentre',
    storageBucket: 'ed-sentre.firebasestorage.app',
    iosBundleId: 'com.tech.edSentreTecherAndParent',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeieJgC9ieJtEeobM2CaihrxdrcX593qc',
    appId: '1:941281553238:web:0f8667db8a0b34872284f7',
    messagingSenderId: '941281553238',
    projectId: 'ed-sentre',
    authDomain: 'ed-sentre.firebaseapp.com',
    storageBucket: 'ed-sentre.firebasestorage.app',
  );
}
